/**
 * database.ts
 *
 * Hand-written TypeScript types that mirror the SQL schema defined in
 * supabase/migrations/0001_core_tenancy.sql.
 *
 * These types are intentionally simple plain interfaces - no generated
 * Database wrapper required at this stage.  Update them whenever the
 * underlying schema changes.
 */

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export type UserRole =
  | 'super_admin'
  | 'restaurant_owner'
  | 'restaurant_staff'
  | 'visitor';

// ---------------------------------------------------------------------------
// Tenant
// ---------------------------------------------------------------------------

export type TenantStatus = 'active' | 'suspended' | 'pending';

export interface Tenant {
  /** UUID primary key, generated by the database. */
  id: string;
  /**
   * URL-safe slug used as subdomain identifier.
   * Lowercase alphanumeric + hyphens, 3–63 characters.
   */
  slug: string;
  /** Human-readable display name of the restaurant / tenant. */
  name: string;
  /** Optional custom domain pointing at this tenant (unique). */
  custom_domain: string | null;
  /** Lifecycle status of the tenant. */
  status: TenantStatus;
  created_at: string; // ISO-8601 timestamptz returned as string by Supabase JS
  updated_at: string;
}

// ---------------------------------------------------------------------------
// Profile
// ---------------------------------------------------------------------------

export interface Profile {
  /**
   * Same UUID as auth.users(id).
   * Created automatically by the on_auth_user_created trigger.
   */
  id: string;
  /** Platform-wide role assigned to this user. */
  role: UserRole;
  /**
   * Tenant this user belongs to.
   * Required (non-null) for restaurant_owner and restaurant_staff.
   * Must be null for super_admin and visitor.
   */
  tenant_id: string | null;
  /** Display name copied from auth metadata on sign-up; editable thereafter. */
  full_name: string | null;
  created_at: string;
  updated_at: string;
}

// ---------------------------------------------------------------------------
// Module (platform-wide catalog - 0002_modules_pricing.sql)
// ---------------------------------------------------------------------------

export type BillingPeriod = 'monthly' | 'yearly' | 'one_time';

export interface Module {
  /** Machine key - lowercase snake_case, matches '^[a-z][a-z0-9_]*$'. */
  id: string;
  /** Human-readable display name of the module. */
  name: string;
  /** Optional description shown in the admin module catalog. */
  description: string | null;
  /** Platform base price in cents (0 = included in all plans). */
  base_price_cents: number;
  /** Billing recurrence for this module. */
  billing_period: BillingPeriod;
  /** When false the module is hidden and cannot be enabled for any tenant. */
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

// ---------------------------------------------------------------------------
// TenantModule (per-tenant feature flag - 0002_modules_pricing.sql)
//
// NOTE: price_override_cents is only visible to tenant owners/staff and
// super_admin via public.get_tenant_module_pricing().  Anon and general
// authenticated callers receive only the safe column subset defined by the
// column grant (tenant_id, module_id, enabled, enabled_at).
// ---------------------------------------------------------------------------

export interface TenantModule {
  /** UUID of the tenant this row belongs to. */
  tenant_id: string;
  /** Module identifier referencing public.modules(id). */
  module_id: string;
  /** Whether this module is currently active for the tenant. */
  enabled: boolean;
  /**
   * Per-tenant price override in cents.
   * null means "charge base_price_cents from the modules table".
   * Only readable via get_tenant_module_pricing() for authorised callers.
   */
  price_override_cents: number | null;
  /** Timestamp when the module was last enabled (null if never enabled). */
  enabled_at: string | null;
  created_at: string;
  updated_at: string;
}

// ---------------------------------------------------------------------------
// TenantModulePricing - return type of public.get_tenant_module_pricing()
// ---------------------------------------------------------------------------

export interface TenantModulePricing {
  /** Module identifier. */
  module_id: string;
  /** Whether this module is currently enabled for the tenant. */
  enabled: boolean;
  /** Per-tenant price override in cents (null = use base price). */
  price_override_cents: number | null;
  /** Platform base price in cents. */
  base_price_cents: number;
  /** Resolved price: coalesce(price_override_cents, base_price_cents). */
  effective_price_cents: number;
}

// ---------------------------------------------------------------------------
// SiteSettings (per-tenant site design - 0003_site_settings.sql)
// ---------------------------------------------------------------------------

/**
 * All web-font families supported by the platform.
 * Must stay in sync with the SQL allowlist check in 0003_site_settings.sql.
 */
export const SITE_FONTS = [
  'Inter',
  'Lora',
  'Playfair Display',
  'Roboto',
  'Open Sans',
  'Montserrat',
  'Merriweather',
] as const;

/** Union of all valid font family strings. */
export type SiteFont = (typeof SITE_FONTS)[number];

export interface SiteSettings {
  /**
   * UUID of the owning tenant.  This is also the primary key - one row per
   * tenant.  Matches public.tenants(id).
   */
  tenant_id: string;
  /**
   * Public URL of the tenant's logo image in the tenant-assets storage bucket.
   * Null until the owner uploads a logo.
   */
  logo_url: string | null;
  /**
   * Public URL of the hero / banner image.
   * Null until the owner uploads one.
   */
  hero_image_url: string | null;
  /**
   * Primary brand colour in CSS hex notation (#rrggbb).
   * Default: '#1a1a1a'.
   */
  primary_color: string;
  /**
   * Secondary brand colour in CSS hex notation (#rrggbb).
   * Default: '#f5f5f5'.
   */
  secondary_color: string;
  /**
   * Accent / highlight colour in CSS hex notation (#rrggbb).
   * Default: '#e11d48'.
   */
  accent_color: string;
  /** Font family used for headings.  Must be a member of SITE_FONTS. */
  font_heading: SiteFont;
  /** Font family used for body text.  Must be a member of SITE_FONTS. */
  font_body: SiteFont;
  /**
   * Short tagline shown on the restaurant microsite.
   * Maximum 200 characters; null until set.
   */
  tagline: string | null;
  /**
   * Long-form "About us" text.
   * Maximum 2000 characters; null until set.
   */
  about: string | null;
  /**
   * Social-media links stored as a plain JSON object.
   * Keys are platform names (e.g. "instagram", "facebook") and values are URLs.
   * Defaults to an empty object {}.
   */
  social: Record<string, string>;
  created_at: string;
  updated_at: string;
}

// ---------------------------------------------------------------------------
// Menu (0004_menu.sql)
// ---------------------------------------------------------------------------

/**
 * All allergen codes recognised by the platform.
 * Must stay in sync with the dishes_allergens_valid CHECK in 0004_menu.sql.
 */
export const ALLERGENS = [
  'gluten',
  'dairy',
  'eggs',
  'fish',
  'shellfish',
  'tree_nuts',
  'peanuts',
  'soy',
  'sesame',
  'celery',
  'mustard',
  'sulphites',
] as const;

/** Union of all valid allergen code strings. */
export type Allergen = (typeof ALLERGENS)[number];

export interface MenuCategory {
  /** UUID primary key, generated by the database. */
  id: string;
  /** UUID of the owning tenant. */
  tenant_id: string;
  /** Display name of the category (1–80 characters). */
  name: string;
  /** Optional description of the category (max 500 characters). */
  description: string | null;
  /** Display order within the tenant's menu (ascending). */
  sort_order: number;
  /** When false the category is hidden from the public menu. */
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface Dish {
  /** UUID primary key, generated by the database. */
  id: string;
  /**
   * UUID of the owning tenant.
   * Denormalized from menu_categories for RLS performance.
   * Enforced to match category's tenant_id by the check_dish_category_tenant trigger.
   */
  tenant_id: string;
  /** UUID of the parent menu category. */
  category_id: string;
  /** Display name of the dish (1–120 characters). */
  name: string;
  /** Optional description of the dish (max 1000 characters). */
  description: string | null;
  /** Price in integer cents (0 = free/included). */
  price_cents: number;
  /** Public URL of the dish photo in the tenant-assets bucket; null until set. */
  photo_url: string | null;
  /**
   * List of allergen codes present in this dish.
   * All values must be members of ALLERGENS.
   * Defaults to empty array.
   */
  allergens: Allergen[];
  /** When false the dish is hidden from the public menu. */
  is_available: boolean;
  /** Display order within the category (ascending). */
  sort_order: number;
  created_at: string;
  updated_at: string;
}

// ---------------------------------------------------------------------------
// Floor Plans (0005_floor_plans.sql)
// ---------------------------------------------------------------------------

/**
 * Discriminated union describing the clickable area of a table on the floor map.
 *
 * rect   - axis-aligned rectangle: top-left corner (x, y), width w, height h.
 * circle - circle: centre (cx, cy), radius r.
 *
 * All numeric values are in the logical coordinate space defined by the parent
 * floor_plan's (width, height) dimensions.
 */
export type TableZone =
  | { type: 'rect';   x: number;  y: number;  w: number; h: number }
  | { type: 'circle'; cx: number; cy: number; r: number };

export interface FloorPlan {
  /** UUID primary key, generated by the database. */
  id: string;
  /** UUID of the owning tenant. */
  tenant_id: string;
  /** Display name of the floor plan (1–80 characters), e.g. "Main Hall". */
  name: string;
  /**
   * Public URL of the background photo in the tenant-assets bucket.
   * Null until the owner uploads one.
   */
  image_url: string | null;
  /**
   * Logical coordinate space width in pixels.
   * Zone coordinates are expressed in these units (100–10 000).
   */
  width: number;
  /**
   * Logical coordinate space height in pixels.
   * Zone coordinates are expressed in these units (100–10 000).
   */
  height: number;
  /** When false the plan is hidden from the public floor map. */
  is_active: boolean;
  /** Display order when multiple plans exist (ascending). */
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface FloorTable {
  /** UUID primary key, generated by the database. */
  id: string;
  /**
   * UUID of the owning tenant.
   * Denormalized from floor_plans for RLS performance.
   * Enforced to match floor_plan's tenant_id by the check_table_plan_tenant trigger.
   */
  tenant_id: string;
  /** UUID of the parent floor plan. */
  floor_plan_id: string;
  /** Short label shown on the map (1–20 characters), e.g. "T1". */
  label: string;
  /** Maximum number of seated guests (1–50). */
  capacity: number;
  /** Geometric descriptor of the clickable zone on the floor map. */
  zone: TableZone;
  /**
   * When false the table cannot be booked but is still rendered on the public
   * map as an unavailable zone.
   */
  is_bookable: boolean;
  created_at: string;
  updated_at: string;
}

// ---------------------------------------------------------------------------
// Reservations (0006_reservations.sql)
// ---------------------------------------------------------------------------

/**
 * Weekly availability rule for a tenant.
 * One row per (tenant_id, weekday) - UNIQUE constraint enforces the simple
 * single-shift model (split shifts are out of scope).
 *
 * weekday follows JavaScript's Date.getDay() convention: 0 = Sunday, 6 = Saturday.
 */
export interface AvailabilityRule {
  /** UUID primary key, generated by the database. */
  id: string;
  /** UUID of the owning tenant. */
  tenant_id: string;
  /**
   * Day of the week: 0 (Sunday) … 6 (Saturday).
   * Matches JavaScript's Date.getDay() convention.
   */
  weekday: number;
  /**
   * Time the venue opens on this weekday, in "HH:MM:SS" format.
   * Always earlier than closes_at (enforced by DB CHECK).
   */
  opens_at: string;
  /**
   * Time the venue closes on this weekday, in "HH:MM:SS" format.
   * Always later than opens_at (enforced by DB CHECK).
   */
  closes_at: string;
  /**
   * Slot granularity in minutes.
   * One of 15, 30, or 60.
   */
  slot_minutes: 15 | 30 | 60;
  /**
   * How many minutes before closes_at the last available booking slot begins.
   * Range: 0–480.  Default: 90.
   */
  last_seating_minutes: number;
  /**
   * When true this weekday is fully closed.
   * opens_at / closes_at are stored but ignored by the availability engine.
   */
  is_closed: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * Per-tenant scalar booking configuration.
 * One row per tenant (PK = tenant_id FK); auto-created by trigger on tenant INSERT.
 */
export interface ReservationSettings {
  /**
   * UUID of the owning tenant.  This is also the primary key - one row per
   * tenant.  Matches public.tenants(id).
   */
  tenant_id: string;
  /**
   * Maximum guests allowed in a single booking (1–100).
   * Default: 12.
   */
  max_party_size: number;
  /**
   * Earliest a booking may be submitted, expressed as minutes from now.
   * Default: 60.
   */
  min_advance_minutes: number;
  /**
   * Latest a booking may be submitted, expressed as days from today.
   * Default: 60.
   */
  max_advance_days: number;
  /**
   * Default duration used when computing ends_at for a new booking, in minutes.
   * Range: 15–480.  Default: 90.
   */
  default_duration_minutes: number;
  created_at: string;
  updated_at: string;
}

/**
 * Lifecycle status of a reservation.
 * Must stay in sync with the reservations_status_values CHECK in 0006_reservations.sql.
 */
export type ReservationStatus =
  | 'pending'
  | 'confirmed'
  | 'cancelled'
  | 'completed'
  | 'no_show';

export interface Reservation {
  /** UUID primary key, generated by the database. */
  id: string;
  /**
   * UUID of the owning tenant.
   * Denormalized for RLS performance.
   * Enforced to match floor_table's tenant_id by the check_reservation_table_tenant trigger.
   */
  tenant_id: string;
  /**
   * UUID of the specific physical table assigned to this booking.
   * Null when no specific table is assigned ("unassigned" / any table).
   * SET NULL when the floor_table row is deleted (historical record preserved).
   * When non-null, the DB EXCLUSION constraint prevents double-booking.
   */
  floor_table_id: string | null;
  /**
   * UUID referencing auth.users(id).
   * Null for guest bookings created via the server-side API (TASK-019).
   * SET NULL when the user account is deleted.
   */
  user_id: string | null;
  /**
   * Full name of the guest making the booking (1–120 characters).
   * Required even for authenticated users (denormalized for dashboard display).
   */
  guest_name: string;
  /**
   * Email address of the guest.
   * Basic format enforced by DB CHECK (position('@') > 1).
   * Null if not provided.
   */
  guest_email: string | null;
  /**
   * Phone number of the guest (5–40 characters).
   * Null if not provided.
   */
  guest_phone: string | null;
  /** Number of guests in the party (1–100). */
  party_size: number;
  /** ISO-8601 timestamptz: when the booking window starts (UTC). */
  starts_at: string;
  /** ISO-8601 timestamptz: when the booking window ends (UTC). */
  ends_at: string;
  /** Lifecycle status of the reservation. */
  status: ReservationStatus;
  /**
   * Optional free-text notes from the guest or staff.
   * Maximum 1000 characters; null if not provided.
   */
  notes: string | null;
  created_at: string;
  updated_at: string;
}

// ---------------------------------------------------------------------------
// Shared monetary types (used across events, delivery, and orders)
// ---------------------------------------------------------------------------

/**
 * ISO 4217 currency codes accepted by the platform.
 * Must stay in sync with the currency CHECK constraints across all migrations
 * that carry a currency column (0007_events.sql, 0008_delivery.sql,
 * 0009_orders.sql).
 */
export type Currency = 'usd' | 'eur' | 'gbp' | 'rub';

// ---------------------------------------------------------------------------
// Delivery (0008_delivery.sql)
// ---------------------------------------------------------------------------

/**
 * ISO 4217 currency codes accepted by the platform.
 * @deprecated Alias of the canonical Currency type.  Use Currency directly.
 */
export type DeliveryCurrency = Currency;

/**
 * One entry in the delivery_settings.schedule jsonb object.
 * Keys "0"–"6" (Sunday–Saturday, JS Date.getDay() convention).
 * All times are UTC.
 */
export interface DeliveryScheduleDay {
  /** Wall-clock opening time in "HH:MM" format (UTC). */
  open: string;
  /** Wall-clock closing time in "HH:MM" format (UTC). */
  close: string;
  /** When true this day accepts no delivery orders regardless of open/close. */
  closed: boolean;
}

/**
 * Shape of delivery_settings.schedule.
 * Keys are weekday numbers as strings ("0" = Sunday … "6" = Saturday).
 * Missing keys are treated as closed days by the application layer.
 * {} is the canonical "not yet configured" sentinel (the DB default).
 */
export type DeliverySchedule = Partial<Record<'0' | '1' | '2' | '3' | '4' | '5' | '6', DeliveryScheduleDay>>;

/**
 * Per-tenant delivery configuration.
 * Singleton - one row per tenant (auto-created by trigger on tenant INSERT).
 * Primary key is a standalone uuid (id), not PK=FK, with a UNIQUE NOT NULL FK
 * on tenant_id.
 */
export interface DeliverySettings {
  /** UUID primary key, generated by the database. */
  id: string;
  /**
   * UUID of the owning tenant.
   * UNIQUE - enforces the one-row-per-tenant singleton.
   * Matches public.tenants(id).
   */
  tenant_id: string;
  /**
   * Master delivery switch.
   * When false no delivery orders are accepted.
   * Default: false.
   */
  is_enabled: boolean;
  /**
   * Minimum basket value in integer cents required for a delivery order.
   * 0 = no minimum.  Range: 0–10,000,000.
   * Default: 0.
   */
  min_order_cents: number;
  /**
   * Flat delivery fee in integer cents when no zone fee_override_cents applies.
   * 0 = free delivery by default.  Range: 0–1,000,000.
   * Default: 0.
   */
  base_fee_cents: number;
  /**
   * Order subtotal threshold in integer cents at or above which delivery is free.
   * null = no free-delivery tier.  Range when non-null: 0–10,000,000.
   */
  free_delivery_over_cents: number | null;
  /**
   * ISO 4217 currency code for all monetary values in this tenant's delivery flow.
   * One of 'usd' | 'eur' | 'gbp' | 'rub'.
   * Default: 'usd'.
   */
  currency: DeliveryCurrency;
  /**
   * Per-weekday delivery window configuration (UTC).
   * Shape: { "0": { open: "HH:MM", close: "HH:MM", closed: bool }, ... }
   * Keys 0–6 correspond to Sunday–Saturday.  Missing keys are treated as closed
   * days.  {} means "not yet configured".
   */
  schedule: DeliverySchedule;
  /**
   * Estimated delivery time in minutes shown to customers at checkout.
   * null = not displayed.  Range when non-null: 5–480.
   */
  estimated_minutes: number | null;
  created_at: string;
  updated_at: string;
}

/**
 * A named delivery zone belonging to a tenant.
 * Multiple rows per tenant.  Each zone optionally carries a geo-polygon and
 * per-zone fee / minimum-order overrides.
 *
 * For TASK-027 (orders): add a nullable delivery_zone_id uuid FK referencing
 * this table with ON DELETE SET NULL to link an order to the zone it was
 * placed in without destroying order history on zone deletion.
 */
export interface DeliveryZone {
  /** UUID primary key, generated by the database. */
  id: string;
  /** UUID of the owning tenant. */
  tenant_id: string;
  /**
   * Human-readable zone name (1–80 characters).
   * UNIQUE per tenant - constraint name: delivery_zones_tenant_id_name_key
   * (used for 23505 duplicate-name error mapping in TASK-028).
   */
  name: string;
  /**
   * Delivery boundary expressed as an array of [longitude, latitude] pairs.
   * Shape: [[lng0, lat0], [lng1, lat1], ...]
   * null = zone has no map boundary (named area without a drawn polygon).
   * When non-null: ≥3 points, each a 2-number array (enforced by DB trigger).
   */
  polygon: [number, number][] | null;
  /**
   * Per-zone delivery fee override in integer cents.
   * null = use delivery_settings.base_fee_cents for orders in this zone.
   * 0 = free delivery for this zone.  Range when non-null: 0–1,000,000.
   */
  fee_override_cents: number | null;
  /**
   * Per-zone minimum order value override in integer cents.
   * null = use delivery_settings.min_order_cents for orders in this zone.
   * Range when non-null: 0–10,000,000.
   */
  min_order_override_cents: number | null;
  /**
   * When false the zone is suspended without deletion.
   * Inactive zones are hidden from the public B2C map (RLS).
   * Default: true.
   */
  is_active: boolean;
  /** Display order when listing zones in the admin dashboard (ascending). */
  sort_order: number;
  created_at: string;
  updated_at: string;
}

// ---------------------------------------------------------------------------
// Orders (0009_orders.sql)
// ---------------------------------------------------------------------------

/**
 * Discriminant for the three PLAN order flows.
 * Must stay in sync with the orders_order_type_values CHECK in 0009_orders.sql.
 *
 * 'in_session' - dine-in order tied to a physical table (table_id).
 * 'delivery'   - off-premise order with a delivery address and zone.
 * 'banquet'    - pre-order tied to a reservation (deposit via TASK-031).
 */
export type OrderType = 'in_session' | 'delivery' | 'banquet';

/**
 * Lifecycle status of an order.
 * Must stay in sync with the orders_status_values CHECK in 0009_orders.sql.
 *
 * Allowed visitor self-transition (guard trigger enforces): pending → cancelled.
 * Full transition rules (API layer, TASK-029):
 *   pending → confirmed → preparing → ready → completed
 *   ready (delivery) → out_for_delivery → completed
 *   any non-terminal → cancelled
 *   completed → refunded (Stripe webhook, TASK-030)
 */
export type OrderStatus =
  | 'pending'
  | 'confirmed'
  | 'preparing'
  | 'ready'
  | 'out_for_delivery'
  | 'completed'
  | 'cancelled'
  | 'refunded';

/**
 * A customer order in one of three flows: in-session (dine-in), delivery,
 * or banquet pre-order.
 *
 * All money columns are integer cents; total_cents is enforced by DB CHECK
 * to equal subtotal_cents + delivery_fee_cents.
 */
export interface Order {
  /** UUID primary key, generated by the database. */
  id: string;
  /**
   * UUID of the owning tenant.
   * Denormalized for RLS performance.
   */
  tenant_id: string;
  /** Discriminant for the three order flows. */
  order_type: OrderType;
  /** Lifecycle status of the order. */
  status: OrderStatus;
  /**
   * UUID referencing auth.users(id).
   * Null for guest orders created via the service-role API (TASK-029).
   * SET NULL when the user account is deleted.
   */
  user_id: string | null;
  /**
   * Full name of the customer placing the order (1–120 characters).
   * Required even for authenticated users (PII snapshot).
   */
  customer_name: string;
  /**
   * Email address of the customer (max 254 characters).
   * No format check at the DB layer - validated by zod/API.
   * Null if not provided.
   */
  customer_email: string | null;
  /**
   * Phone number of the customer (max 40 characters).
   * Null if not provided.
   */
  customer_phone: string | null;
  /**
   * UUID of the physical floor table (in_session orders).
   * Null when order_type ≠ 'in_session', or when the table has been freed/deleted.
   * SET NULL when the floor_table row is deleted (order history preserved).
   */
  table_id: string | null;
  /**
   * UUID of the delivery zone the order was placed in (delivery orders).
   * Null when order_type ≠ 'delivery', or when the zone has been deleted.
   * SET NULL when the delivery_zone row is deleted (order history preserved).
   */
  delivery_zone_id: string | null;
  /**
   * Delivery address for delivery orders (max 500 characters).
   * Non-null when order_type = 'delivery' (enforced by DB CHECK).
   * Null for in_session / banquet orders.
   */
  delivery_address: string | null;
  /**
   * UUID of the linked reservation (banquet orders).
   * Null when order_type ≠ 'banquet', or when not yet linked, or after deletion.
   * SET NULL when the reservation row is deleted (order history preserved).
   */
  reservation_id: string | null;
  /**
   * Optional free-text notes (special requests, dietary info, banquet instructions).
   * Max 2000 characters; null if not provided.
   */
  notes: string | null;
  /**
   * Sum of (unit_price_cents × quantity) across all order_items.
   * Range: 0–100,000,000 cents.
   */
  subtotal_cents: number;
  /**
   * Snapshot of the resolved delivery fee in integer cents.
   * 0 for in_session and banquet orders.
   * Resolution logic (zone fee_override_cents vs. settings base_fee_cents,
   * free_delivery_over_cents threshold) performed by TASK-029 before insert.
   * Range: 0–1,000,000 cents.
   */
  delivery_fee_cents: number;
  /**
   * Total amount charged: subtotal_cents + delivery_fee_cents.
   * Enforced by DB CHECK (orders_total_equals_subtotal_plus_fee).
   * Range: 0–100,000,000 cents.
   */
  total_cents: number;
  /**
   * ISO 4217 currency code snapshotted from tenant/delivery settings at order time.
   * One of 'usd' | 'eur' | 'gbp' | 'rub'.
   */
  currency: Currency;
  /**
   * Banquet deposit amount in integer cents (TASK-031).
   * 0 = no deposit required.  Range: 0–100,000,000 cents.
   * Default: 0.
   */
  deposit_cents: number;
  /**
   * Stripe payment / charge identifier.
   * Null until payment is initiated (TASK-030).
   * Mirrors event_tickets.payment_ref.
   */
  payment_ref: string | null;
  created_at: string; // ISO-8601 timestamptz
  updated_at: string;
}

/**
 * A single dish line within an order.
 * Dish data (name, price) is snapshotted at order-creation time so that
 * historical records survive menu changes and dish deletions.
 *
 * Items are write-once from the visitor perspective (no visitor UPDATE/DELETE
 * RLS policies).  Staff edits flow through tenant-role policies.
 */
export interface OrderItem {
  /** UUID primary key, generated by the database. */
  id: string;
  /**
   * UUID of the owning tenant.
   * Denormalized for RLS performance.
   * Enforced to match order's tenant_id by the check_order_item_order_tenant trigger.
   */
  tenant_id: string;
  /** UUID of the parent order (references public.orders, CASCADE on delete). */
  order_id: string;
  /**
   * UUID referencing public.dishes(id).
   * Null after the source dish is deleted (ON DELETE SET NULL).
   * The snapshot columns below preserve the historical line data.
   */
  dish_id: string | null;
  /**
   * Snapshot of dishes.name at order creation time (1–160 characters).
   * Preserved even after the dish is deleted or renamed.
   */
  dish_name: string;
  /**
   * Snapshot of dishes.price_cents at order creation time (0–10,000,000 cents).
   * Integrity against live prices validated in TASK-029 API layer.
   */
  unit_price_cents: number;
  /** Number of units of this dish in the order (1–100). */
  quantity: number;
  created_at: string; // ISO-8601 timestamptz
  // No updated_at - items are write-once from the visitor perspective.
}

// ---------------------------------------------------------------------------
// Events (0007_events.sql)
// ---------------------------------------------------------------------------

/**
 * Lifecycle status of an event ticket purchase.
 * Must stay in sync with the event_tickets_status_values CHECK in 0007_events.sql.
 *
 * 'reserved'  - seats held pending payment; capacity is consumed immediately
 *               by the DB check_event_capacity trigger.
 * 'paid'      - payment confirmed (Stripe webhook, TASK-030).
 * 'cancelled' - buyer self-cancelled (reserved only, via visitor RLS + guard
 *               trigger) or staff/owner cancelled.
 * 'refunded'  - payment reversed via Stripe refund flow (TASK-030).
 */
export type EventTicketStatus =
  | 'reserved'
  | 'paid'
  | 'cancelled'
  | 'refunded';

/**
 * A ticketed or free event hosted by a tenant.
 *
 * Named RestaurantEvent to avoid clashing with the DOM global Event type.
 * The underlying SQL table is `public.events`.
 */
export interface RestaurantEvent {
  /** UUID primary key, generated by the database. */
  id: string;
  /** UUID of the owning tenant. */
  tenant_id: string;
  /** Display title of the event (1–160 characters). */
  title: string;
  /**
   * Optional long-form description of the event.
   * Maximum 4000 characters; null until set.
   */
  description: string | null;
  /**
   * Public URL of the event banner/cover image in the tenant-assets bucket.
   * Null until the owner uploads one.
   */
  image_url: string | null;
  /** ISO-8601 timestamptz: when the event starts (UTC). */
  starts_at: string;
  /**
   * ISO-8601 timestamptz: when the event ends (UTC).
   * Null for open-ended events.  When non-null, always later than starts_at
   * (enforced by DB CHECK).
   */
  ends_at: string | null;
  /**
   * Total number of tickets available for this event (1–10 000).
   * Enforced by the check_event_capacity DB trigger: the sum of quantity
   * across all reserved+paid event_tickets rows may never exceed this value.
   */
  capacity: number;
  /**
   * Ticket face value in integer cents (0 = free event, max 10 000 000).
   * This is the current price; historical purchases snapshot the value at
   * purchase time in event_tickets.unit_price_cents.
   */
  price_cents: number;
  /**
   * ISO 4217 currency code for this event's tickets.
   * Consumed by Stripe (TASK-030) as the payment currency.
   */
  currency: Currency;
  /**
   * When false the event is in draft mode and hidden from the public listing.
   * Public SELECT RLS policy requires is_published = true.
   */
  is_published: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * A single ticket purchase batch for an event.
 * One row represents a checkout of `quantity` seats made in a single transaction.
 * This maps cleanly to a single Stripe line item (TASK-030).
 */
export interface EventTicket {
  /** UUID primary key, generated by the database. */
  id: string;
  /**
   * UUID of the owning tenant.
   * Denormalized for RLS performance.
   * Enforced to match event's tenant_id by the check_event_ticket_event_tenant trigger.
   */
  tenant_id: string;
  /** UUID of the parent event (references public.events, CASCADE on delete). */
  event_id: string;
  /**
   * UUID referencing auth.users(id).
   * Null for guest purchases created via the service-role API (TASK-023).
   * SET NULL when the user account is deleted.
   */
  user_id: string | null;
  /**
   * Full name of the buyer (1–120 characters).
   * Required; used for confirmation emails and the B2B attendee dashboard.
   */
  buyer_name: string;
  /**
   * Email address of the buyer.
   * Basic format enforced by DB CHECK (position('@') > 1 AND length 3–254).
   * Null if not provided.
   */
  buyer_email: string | null;
  /**
   * Phone number of the buyer (5–40 characters).
   * Null if not provided.
   */
  buyer_phone: string | null;
  /** Number of seats purchased in this batch (1–100). */
  quantity: number;
  /**
   * Snapshot of events.price_cents at the time of purchase (≥ 0).
   * Immutable after creation - the event price may change later without
   * retroactively altering this record.  Integrity of this snapshot for
   * visitor INSERTs is validated in the TASK-023 API layer; the DB trigger
   * enforces capacity but not price correctness.
   */
  unit_price_cents: number;
  /**
   * Snapshot of events.currency at the time of purchase.
   * Immutable after creation - matches the Stripe charge currency.
   */
  currency: Currency;
  /** Lifecycle status of this ticket purchase. */
  status: EventTicketStatus;
  /**
   * Stripe payment / charge identifier.
   * Null until payment is initiated (TASK-030).
   */
  payment_ref: string | null;
  created_at: string;
  updated_at: string;
}
